#!/usr/bin/env sh
# Vendor all crates.io dependencies of the Dora Rust runtime so it builds
# in network-restricted environments (F-Droid, distro packagers,
# reproducible/offline builds).
#
# Usage:
#   Tools/scripts/rust-vendor.sh            # create Source/Rust/vendor
#   Tools/scripts/rust-vendor.sh --remove   # go back to network builds
#
# After vendoring, cargo automatically picks up Source/Rust/.cargo/config.toml
# (created by this script) and the xmake dora-rust-runtime target builds with
# --offline. The vendor/ tree is ~100 MB with every target platform included
# (mostly windows-* crates pulled in by clap's terminal backend), which is why
# it is generated on demand instead of committed; the Go module tree under
# Tools/dora-wa/vendor is small enough to live in the repository.
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
RUST_DIR="$ROOT/Source/Rust"

if [ "${1:-}" = "--remove" ]; then
	rm -rf "$RUST_DIR/vendor" "$RUST_DIR/.cargo"
	echo "Removed vendored crates; builds now fetch from crates.io."
	exit 0
fi

cd "$RUST_DIR"
command -v cargo >/dev/null || { echo "cargo not found in PATH" >&2; exit 1; }

cargo vendor vendor

mkdir -p .cargo
cat > .cargo/config.toml << 'EOF'
# Generated by Tools/scripts/rust-vendor.sh — do not edit or commit.
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

echo "Vendored crates into Source/Rust/vendor (~100 MB) and wrote Source/Rust/.cargo/config.toml."
echo "Offline builds are now active; revert with Tools/scripts/rust-vendor.sh --remove."
